### ISSUE TITLE
Lifecycle binaries contain using Go Standard Lib with critical CVE

### ISSUE THREAD

**Issue by matthewrobertson** [buildpacks/lifecycle#1082]
A critical CVE has been discovered in the Go standard library: https://security-tracker.debian.org/tracker/CVE-2023-24538

Version 0.16.1 of the lifecycle binaries were built with a Go version that includes the CVE. I am not sure if Grype detects CVEs in Go standard lib, but Google's Container Analysis scanner reports it. 

<img width="1063" alt="Screenshot 2023-05-05 at 9 40 48 AM" src="https://user-images.githubusercontent.com/644493/236516962-35015e89-1852-4fa7-a916-5a0af3e193f9.png">

Also see: https://github.com/GoogleCloudPlatform/buildpacks/issues/298

**Comment by natalieparellano** [comment]
Thanks for reporting @matthewrobertson - we'll work on getting a patch out

**Comment by matthewrobertson** [comment]
let me know if I can help

**Comment by natalieparellano** [comment]
This is resolved in lifecycle 0.16.3 (not 0.16.2, that mistakenly has go 1.19.8 instead of go 1.19.9). We are fairly confident the noted CVE (in the html/template package, which we don't import) doesn't affect the lifecycle however given the severity level of critical and the difficulty in definitively proving and communicating this to our end-users we decided a patch was warranted.
