### ISSUE TITLE
how can i get time-cost from different phase

### ISSUE THREAD

**Issue by TigerWj** [buildpacks/lifecycle#1153]
hi, I'm using /lifecycle/creator to run build  instead of pack，and i need to statistic the time-cost from differe phase，like analyse / export，so how can I do it?  it seems there are no metric log that can use

**Comment by joe-kimmel-vmw** [comment]
Hi @TigerWj  -- Thanks for filing this issue as it's a very helpful signal.    @natalieparellano and I have been talking about this from a few different angles for a little while, and it's great to know that someone else is interested too!

First -- in general the creator will always be faster than running the individual phases, just because it means you're only starting one executable instead of starting separate processes for each phase.   But I think you're really asking for a high-level "profiling" overview that shows how long each phase takes?

One strategy for getting this would be to add some info level logging to the beginning and end of each phase, right? 
in that vein, you can see some recent PRs that will be part of the next lifecycle release (0.17) where we're already moving in that direction (such as [this one](https://github.com/buildpacks/lifecycle/pull/1106)

Another strategy would be to add a command-line flag that would turn on golang's profiling tool and output pprof files for each phase.  These would have a lot of information about where time is spent within each phase and would likely require a little familiarity with the codebase and/or golang profiling to work with. 

Another strategy would be to explicitly collect the length of time of each phase and output that into the logs. 

Can you help us understand your specific goals in measuring the times of the phases, and whether any or all of the above would be helpful?

**Comment by TigerWj** [comment]
@joe-kimmel-vmw  thanks. I think the first strategy, add some info level logging to the beginning and end of each phase, is useful. and it is what i exactly did in local.I'am trying  use buildpack in a build sysytem，so it's important for me to make the times of differ pahses clear, without this, it is hard to make optimization. And I think it will be useful for everyone。
the second strategy, sounds a bit complicated,  i think it good for someone who need to measuring times for every action inside each pahse.

**Comment by samj1912** [comment]
@joe-kimmel-vmw we would be interested in this as well. One potential option is report.toml. It would be great if lifecycle can populate phase information there.

**Comment by matejvasek** [comment]
@TigerWj Do you experience any performance issues?
If you really want to tune performance I would recommend compiling lifecycle image with profiling enabled. We talked about it in https://github.com/buildpacks/lifecycle/issues/1007. Recipe how to do it is in this [gist](https://gist.github.com/matejvasek/361e8a63dd600ed18398bdb93004794c#basic-build). Of course this will only dump accurate samples for lifecycle binary, for buildpack's `bin/[detect|build]` execution you will only see it is waiting in `os/exec` package.

IMO there is a good change that most of the time is spent in `bin/[detect|build]`  of some buildpack, if that's the case you need to put debug output there, not just in lifecycle.

**Comment by joe-kimmel-vmw** [comment]
I'm leaving this issue open as it could still be of interest to add some coarse-grained profiling/timing to the report.toml as @samj1912 mentioned.  I've added log messages [here](https://github.com/buildpacks/lifecycle/pull/1160) and will cherry-pick them into our next 0.17 RC.

**Comment by natalieparellano** [comment]
Closed in #1160
