### ISSUE TITLE
Consider making $HOME = /app

### ISSUE THREAD

**Issue by josegonzalez** [buildpacks/lifecycle#123]
In v2 buildpacks, the `$HOME` directory was typically `/app`. This was useful for cases where - for whatever reason - the entire path to a file had to be specified during the running of an application. A good example is the `Procfile` entry for some `R` buildpacks, where the fullpath had to be used because of `fakechroot` usage.

Switching from `/workspace` back to `/app` may increase compatibility with older apps by decreasing the number of changes necessary to migrate from v2 to v3 buildpacks.

**Comment by jkutner** [comment]
In the `heroku/pack:18` image used by the `heroku/buildpacks` builder image, there is a symlink from `/app` to `/workspace`, and `/workspace` is the HOME. We build our run-image with:

```Dockerfile
RUN ln -s /workspace /app

RUN useradd -u ${pack_uid} -g ${pack_gid} -ms /bin/bash -d /workspace heroku
```

(note: the Heroku builds never happened in `/app` so we don't need it in the build image)

This works pretty well with all the Heroku buildpacks that use the [cnb-shim](https://github.com/heroku/cnb-shim).

I think this approach is good: accommodate it in the stack image. I would like to move away from `/app` because we often hear from users that they aren't building an "app" (it's a "service" or something).

**Comment by jkutner** [comment]
that said, i think setting `HOME` as `/workspace` (or whatever is configured in place of `/workspace`) makes sense. But IIRC, there is some reason we can't introduce that to the spec.

**Comment by sclevine** [comment]
Where are you setting `HOME` to workspace in the Heroku images?

Setting `HOME` to `/workspace` during build seems risky to me. Tools often use dot-files in `HOME` to cache downloads (not necessary for launch) or store credentials (bad for security if they end up in the final image).

**Comment by jkutner** [comment]
@sclevine I'm only suggestion we set HOME to `/workspace` for the run-image

**Comment by nebhale** [comment]
I agree with @sclevine on this that given how many runtimes expose the root of the application (think exploded JAR/WAR files) that overlapping `$HOME` with the application directory is problematic.  For reference the only CVE ever opened against the CF Java Buildpack was due to this very behavior ☹️

**Comment by ekcasey** [comment]
Given the concerns @sclevine @nebhale have outlined and the lack of activity on this issue, I am going to go ahead and close it.

Feel free to reopen if you would like to restart the discussion.
