### ISSUE TITLE
launcher fails to properly append args to startcommand

### ISSUE THREAD

**Issue by ForestEckhardt** [buildpacks/lifecycle#218]
If I have the following in my `/layers/config/metadata.toml`
```
[[processes]]
  type = "web"
  command = "yarn"
  args = ["start"]
  direct = false
```

When I `docker run` the image and invoke `/cnb/lifecycle/launcher`, we fail to properly append args to the command [here](https://github.com/buildpacks/lifecycle/blob/b9dc1bd64e7f9c001139c80cbfa884951599451e/launcher.go#L53). As a result the docker run is equivalent to just executing `yarn` instead of the desired `yarn start`

Looks like this is an issue getting `args` to be properly escaped in bash.

**Comment by jromero** [comment]
After digging into it, it appears this is simply a misunderstanding of how the `processes` configuration works. The spec might need a little work to make it more clear but essentially when `direct = false`, the `args` are not arguments to the command but arguments to `bash`.

By example:

```
[[processes]]
  type = "web"
  command = "echo"
  args = ["hello"]
  direct = false
```

would yield:
```
$ bash -c "echo" hello
> 
```
instead of the desired: 
```
$ bash -c "echo hello"
> hello
```

A way to achieve the desired effect would be to use variables in such a way:

```
[[processes]]
  type = "web"
  command = "echo $0"
  args = ["hello"]
  direct = false
```

Alternatively, when `direct = true`, then `args` are arguments to the `command` but keep in mind that you would lose all shell enabled capabilities.

**Comment by jromero** [comment]
@ForestEckhardt, going to close this issue. 

Let us know if you have any other concerns or questions.
