### ISSUE TITLE
Discuss: Does analyze need root access?

### ISSUE THREAD

**Issue by Zanadar** [buildpacks/lifecycle#227]
Discuss: Does analyze need root access?

**Comment by ekcasey** [comment]
@Zanadar when analyzing from or exporting to a docker daemon, the lifecycle sometimes needs to connect to a docker socket mounted by the platform. This requires root access.

The decision to run as `root` or another user is made by the platform. `pack` for example run as the `cnb` user when `--publish` is passed, and root otherwise.

**Comment by ameyer-pivotal** [comment]
@ekcasey Thanks for the clarification
