### ISSUE TITLE
Request: provide API information in releases

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#284]
## Summary

As a user, I'd like to know what version of the platforms API and/or buildpack API any given release of the lifecycle supports from the releases page.

As a platform maintainer, I'd like to be able to automate our platform to download and use the latest version of lifecycle that supports a supported platform API version. In order to do this programmatically, it would be ideal to have the support Platform API version as part of data on releases which is parsable.

## Proposed Solution

1. Add supported APIs to the body of the release notes. 
2. Add artifacts `PLATFORM_API` and `BUILDPACK_API` each with [label](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) of the comma delimited versions supported. eg.
    ```text
    POST :server/repos/:owner/:repo/releases/:release_id/assets?name=PLATFORM_API&label=0.2
    POST :server/repos/:owner/:repo/releases/:release_id/assets?name=BUILDPACK_API&label=0.2,0.3
    ```

**Comment by jromero** [comment]
Thinking about it further, 2) is likely an overcomplication. Although it provides a very structured mechanism it is not optimal as it would require `n+1` requests where `n` is the number of releases until a matching supported version is found. 

If the data was parsable from within the `body` of the releases there would only be a need to do one request.

**Comment by dfreilich** [comment]
It looks like this is done, and can be closed.

**Comment by ekcasey** [comment]
The API information has been added to the body of the release (although it was added with a human audience in mind not a platform). Because we now support multiple APIs I believe that `pack` should be able to safely assume the newest lifecycle supports the desired platform API. By the time any given platform API is deprecated or eventually removed the version of `pack` using that API would be verrry out of date (if indeed we _ever_ remove support for older APIs).
