### ISSUE TITLE
Failure to set `CNB_REGISTRY_AUTH` results in failure to initialize cache in some scenarios

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#339]
### Summary
Today if you run `analyzer some-image` with no flags you will get the following error:
```
ERROR: failed to get previous image: /root/.docker/config.json: stat /root/.docker/config.json: permission denied
```

The following succeeds: `analyzer --env CNB_REGISTRY_AUTH={} some-image`

---

##### Expected
`analyzer some-image` without any flags should succeed.

---

### Context

There are two places where this error can occur:

* `analyzeArgs.analyze()` (registry case)
  * When looking up the previous image - failure to set `CNB_REGISTRY_AUTH` causes us to use the default keychain, we then to proceed to stat `/root/.docker/config.json` after dropping privileges
* `analyzeCmd.Exec()` -> `cache.NewImageCacheFromName()` (cache image case)
  * Same situation as above but occurs when setting up the cache

This doesn't crop up in the wild because in `pack` we always set `CNB_REGISTRY_AUTH` when using the registry. In Tekton we override the docker config directory. But I am sure it will confuse some people. We should fix this.

##### lifecycle version
It is an issue as of v0.8.1

**Comment by natalieparellano** [comment]
When this is fixed we should remove the unneeded `--env CNB_REGISTRY_AUTH={}` in acceptance/analyzer_test.go

**Comment by ekcasey** [comment]
After investigation it seems like the best solution to this issue involves some behavior changes in addition to the bugfix. Therefore we are moving this from the next patch (v0.9.1) to the next minor (v0.9.2).

Proposed solution:
1. `auth.NewKeychain` should return a `MultiKeychain` which
     1. Uses `CNB_REGISTRY_AUTH`, if available
     2. Fall back to auth config from docker `config.json`
2. Because `config.json` may be root owned `NewKeychain` should resolve the correct auth header for any relevent registry and store these in memory before dropping privileges.
