### ISSUE TITLE
Windows app images do not handle signals properly

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#360]
### Summary
On windows signals to the `launcher` are not forwarded to the launched process

---

##### Steps

1. `pack build` a windows app image
2. `docker run` the image
3. CTL+C

##### Current behavior
Container is not stopped

![Screen Shot 2020-08-03 at 12 24 23 PM](https://user-images.githubusercontent.com/1994518/89205227-64feac80-d585-11ea-9331-46914b685dfe.png)

##### Expected
Container should be stopped

---

##### lifecycle version
`main`

##### platform version(s)
`pack` built from the `470-build-windows-images` branch

**Comment by TisVictress** [comment]
@ekcasey We tested this using the main branch of lifecycle.  We are no longer seeing this issue on macos or windows (both using cmd and powershell).  CTRL+c does stop the container.  Feel free to close this issue or ping us if it persists.

**Comment by ekcasey** [comment]
I am stilling seeing this issue in my environment with lifecycle from `main`. I was running a `direct=false` process that starts `hwc.exe` non-interactively. My environment is a MacOS host connected to a windows daemon (the daemon is running in a VM).

Given the number of moving parts here this issue could be unique to my environment... Did you attempt to reproduce with an interactive (docker run -it <image> cmd) or non-interactive container (`docker run <image>`)?

**Comment by ameyer-pivotal** [comment]
@ekcasey We did start seeing this pop up again in our normal testing workflows, so we'll investigate further

**Comment by aemengo** [comment]
@ekcasey @ameyer-pivotal @micahyoung @mvalliath 

> My environment is a MacOS host connected to a windows daemon (the daemon is running in a VM).

I take this to mean that you are connecting to a windows daemon over `DOCKER_HOST` environment variable. If so, you’ll notice that this problem is not CNB related; _any_ container that you try to run (in the same way) will not respect the *CTRL+C*. For example, you could run the following and not see it terminate correctly.

```sh
# export DOCKER_HOST=<IP OF DOCKER HOST>:23750
$ docker run mcr.microsoft.com/windows/nanoserver:1809 ping.exe 127.0.0.1 -n 10
^C^C^C^C^C^C^C
```

This is more likely a result of talking to a Windows daemon in this manner and the commands that the docker CLI is sending. We’ll consider opening up an issue in their repos.

But, for now, the best thing to tell your users is to perform  a `docker stop <container-id>` when iterating on the command-line. Otherwise we can tell to docker run with the `-it` flags.

**Comment by ekcasey** [comment]
Thanks @aemengo. In that case I will close this out.
