### ISSUE TITLE
CacheImage support for daemon images

### ISSUE THREAD

**Issue by dwillist** [buildpacks/lifecycle#484]
### Summary
Currently when passing a `-cache-image <name>` argument to any lifecycle phase, we assume that `<name>` refers to an image on a remote registry.

### Reproduction
call any lifecycle phase with `-cache-image local-cache-image`

This is how I reproduce this error:
- use [this](https://github.com/buildpacks/pack/pull/970) pack PR (or main when it is merged in).
- comment out [these](https://github.com/dwillist/pack/blob/5dd0d792813ca2e4ff2a5ea38189b7bb180888ac/internal/commands/build.go#L186) lines to disable validation to avoid this error.
- build pack
- run `pack build <some-image> -p some-test-app-path --cache-image local-cache-image` 
- see errors when initializing a remote image from [here](https://github.com/buildpacks/lifecycle/blob/ca47d3defd627d7ebb16e5e3b98bb9cc9b2d7ca4/cache/image_cache.go#L39)

Sorry if this is pack-centric I don't have much experience running the lifecycle independently.

##### Current behavior
The following error is produced by pack when running the reproduction steps above:
`failed to create image cache: accessing cache image "index.docker.io/library/local-cache-image:latest": /root/.docker/config.json: stat /root/.docker/config.json: permission denied`

##### Expected
I expected pack to use a local cache image for the `analyze`, `restore`, `export` (& `creator` ) phases

I expected the lifecycle to initialize a `ImageCache` object using a `imgutil.local.Image` image object.

---

##### lifecycle version
`v0.9.3`

##### platform version(s)
PR linked above needed to exercise the `cache-image` flag

**Comment by ekcasey** [comment]
Hey @dwillist we actually supported this in the past and explicitly removed it because of abysmal performance working with the daemon. I think we explicitly want folks to use a volume if they want to store layers in the daemon.

For example, when we export a daemon image will actually [place a volume cache in front of it](https://github.com/buildpacks/lifecycle/blob/main/cache/caching_image.go) to mitigate the performance issues. To make a daemon cache image work acceptably we would probably need to put a volume cache in front of it, but at that point you might as well just use a volume cache.

**Comment by natalieparellano** [comment]
Regarding the surprising error message, this is related to https://github.com/buildpacks/lifecycle/issues/339. Once that is fixed, a daemon cache would be silently ignored (beyond printing a `cache does not exist` info message which we are also adding in the fix for #339). Maybe it's worth adding a more explicit message when someone tries to use a daemon cache? The spec isn't very explicit about where the cache image should be located, so we may want to clarify that as well.

**Comment by dwillist** [comment]
Ya @ekcasey, I totally agree that using `volumes` should really be the default way to do local builds. With pack [adding support for `cache-images`](https://github.com/buildpacks/pack/pull/970) in order to speed up workflows where the build machine is ephemeral, cache images are in an awkward spot. They are only useful on a registry and are completely unusable as a local daemon image. 

A sample use case of using a cache image locally would be: I want to pull down a cache image and use it to debug a failing build in CI.

Also +1ing @natalieparellano  point that only supporting remote images as arguments to `-cache-image` is not mentioned in the spec.

**Comment by ekcasey** [comment]
> A sample use case of using a cache image locally would be: I want to pull down a cache image and use it to debug a failing build in CI.

Why pull it down first when you could just use the remote cache image?

> Also +1ing @natalieparellano point that only supporting remote images as arguments to -cache-image is not mentioned in the spec.

yep, we should make that clearer.

**Comment by natalieparellano** [comment]
Spec PR to clarify that cache image must be in a registry: https://github.com/buildpacks/spec/pull/174

Closing this for now as I don't think local cache images is something we want to support.
