### ISSUE TITLE
[Analyze] Validate registry credentials

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#572]
As outlined in RFC: https://github.com/buildpacks/rfcs/blob/main/text/0075-move-analyze-phase.md

Analyzer should
* Ensure registry read/write access to `<tags>`, `<cache-image>`
* Ensure registry read access to `<previous-image>`, `<run-image>`

**Comment by natalieparellano** [comment]
Blocked on https://github.com/buildpacks/lifecycle/issues/530

**Comment by jjbustamante** [comment]
I'd like to work on this issue

**Comment by jjbustamante** [comment]
Just to leave some notes about my understanding of this issue.

- Ensure registry read/write access to `<tags>`,` <cache-image>`:  The container registry library has a CheckPushPermission that we think we can use to validate the read/write access. I was thinking on expose that method through the [imgutil](https://github.com/buildpacks/imgutil library

- Ensure registry read access to `<previous-image>`, `<run-image>`:  For this one, we already have a method implemented in the [imgutil](https://github.com/buildpacks/imgutil) repository [Found()](https://github.com/buildpacks/imgutil/blob/3ab4c2cd8025ee43e98d15f7fa7eb0ad4e6d6b7e/remote/remote.go#L349) and we can create an Image object with previous-image and run-image and use this method to verify that we actually have read access in the registry

Based on those assumptions, I added the following experimental code on `cmd/lifecycle/analyzer.go` (check for the code between **CODE ADDED comment**)

```
func (a *analyzeCmd) Privileges() error {
	var err error
	a.keychain, err = auth.DefaultKeychain(a.registryImages()...)
	if err != nil {
		return cmd.FailErr(err, "resolve keychain")
	}

	if a.useDaemon {
		var err error
		a.docker, err = priv.DockerClient()
		if err != nil {
			return cmd.FailErr(err, "initialize docker client")
		}

                // ---- CODE ADDED ------
		if a.imageName != "" {
			img, _ := remote.NewImage(a.imageName, a.keychain, remote.WithPreviousImage(a.imageName))
			if !img.Found() {
				return cmd.FailErr(errors.New("**** No read access to image-name ****"))
			}
		}
		if a.runImageRef != "" {
			img, _ := remote.NewImage(a.runImageRef, a.keychain, remote.FromBaseImage(a.runImageRef))
			if !img.Found() {
				return cmd.FailErr(errors.New("**** No read access to run-image ****"))
			}
		}
		if a.platform06.cacheImageTag != "" {
			img, _ := remote.NewImage(a.platform06.cacheImageTag, a.keychain, remote.WithPreviousImage(a.platform06.cacheImageTag))
			if !img.CheckReadWriteAccess() {
				return cmd.FailErr(errors.New("**** No read / write access to cache-image ****"))
			}
		}
                // ---- CODE ADDED ------
	}
	if err := priv.EnsureOwner(a.uid, a.gid, a.layersDir, a.platform06.cacheDir); err != nil {
		return cmd.FailErr(err, "chown volumes")
	}
	if err := priv.RunAs(a.uid, a.gid); err != nil {
		return cmd.FailErr(err, fmt.Sprintf("exec as user %d:%d", a.uid, a.gid))
	}
	return nil
}
```
Also the method added in the imgutil repository is the following: 

```
func (i *Image) CheckReadWriteAccess() bool {
	ref, _, err := referenceForRepoName(i.keychain, i.repoName)
	if err != nil {
		return false
	}
	err = remote.CheckPushPermission(ref, i.keychain, http.DefaultTransport)
	return err == nil
}
```

I haven't tested it yet, I am also open to suggestion on some test cases, but I wanted to share what I have so far in order to get feedback from the community 😄

**Comment by aemengo** [comment]
```
I like

**Comment by natalieparellano** [comment]
> In fact (to express developer intent), maybe we can make a CheckReadAccess() method that just delegates to the Found() method

I love making it more explicit what we are trying to accomplish with this method. My one concern in using `Found()` is that we'll be pulling the manifest when we don't actually need it. I don't see an equivalent `CheckPullPermission` in ggcr but there is a `transport.PullScope` that is used in a number of methods such as `remote.List`, which may give us what we need.

**Comment by jabrown85** [comment]
Looks good! I think you will also need to check `additionalTags` to support the `<tags>` read/write check for additional publish targets.

**Comment by jjbustamante** [comment]
> I love making it more explicit what we are trying to accomplish with this method. My one concern in using `Found()` is that we'll be pulling the manifest when we don't actually need it. I don't see an equivalent `CheckPullPermission` in ggcr but there is a `transport.PullScope` that is used in a number of methods such as `remote.List`, which may give us what we need.

@natalieparellano, if I am not wrong `Found()` is actually doing a HEAD request which is not returning the actual manifest so we are not actually downloading it at this point, I do not see any other cheaper method to validate the access. I checked the [registry API](https://docs.docker.com/registry/spec/api/#detail) and for verifying read access to `<previous-image>`, `<run-image>` I think this one can help us. Also, I can try to build our own `CheckPullPermission()` using the `transport.PullScope` but my question, in this case, is which method from the [registry API](https://docs.docker.com/registry/spec/api/#detail) can help me to do it?

**Comment by natalieparellano** [comment]
@jjbustamante my mistake, I was confusing `Found()` with another method!

**Comment by jjbustamante** [comment]
Hi @jabrown85, @natalieparellano, and all the community, I am working on fixing some acceptance tests that are failing after adding the new validations.

According to the requirement: 
Analyzer should
* Ensure registry read/write access to <tags>, <cache-image>
* Ensure registry read access to <previous-image>, <run-image>

I have several cases, like this one. Basically, we have a READ ONLY registry (the registry returns 405 for any non-read operation), and the lifecycle is invoked with the -cache-image flag with a value pointing to this READ ONLY registry.

For example:

```
TestAnalyzer/acceptance-analyzer/0.3/registry_case/cache_is_provided/cache_image_case/no_auth_registry/restores_cache_metadata

docker.go:58: Expected nil: failed to execute command: 
[docker run --network default --env CNB_PLATFORM_API=0.3 
--name test-container-cxmgubvvwb lifecycle/acceptance/analyzer /cnb/lifecycle/analyzer 
-cache-image 192.168.2.20:55459/some-cache-image-xextxhgnua some-image], 

exit status 1, , POST http://192.168.2.20:55459/v2/some-cache-image-xextxhgnua/blobs/uploads/: 
unexpected status code 405 Method Not Allowed: Method Not Allowed.

ERROR: failed to : read/write image 192.168.2.20:55459/some-cache-image-xextxhgnua from/to the registry
 --- FAIL: TestAnalyzer/acceptance-analyzer/0.3/registry_case/cache_is_provided/cache_image_case/no_auth_registry/restores_cache_metadata (6.92s)
```

As we can see, the new validation is fired, and the test is failing `ERROR: failed to : read/write image 192.168.2.20:55459/some-cache-image-xextxhgnua from/to the registry` I added this error message.

How these new validations affects all the cases where the -cache-image file is pointing to a READ ONLY registry? Are those cases not longer valid? is the read/write validation for -cache-image expected to be valid only for some API versions? I am a little confused here

**Comment by jabrown85** [comment]
Thanks for the details! 

It looks like [the spec](https://github.com/buildpacks/spec/blob/platform/0.7/platform.md) actually only says we need write access to `<image>` and `<tag>`s. `cache-image` and `cache-dir` is actually not an input to `analyzer` on `0.7` platform anymore. This is in conflict with this issue.

But maybe `cache-image` should be added back so that we can validate image access as well. That was the intent, but I think we removed `cache-image` because we weren't initially planning on doing some of this validation in the first phase and having an argument that wasn't in use didn't make sense.

I think those tests should fail like you've shown and be removed. If I'm understanding this correctly, an actual execution using a read only registry for the `cache-image` would result in failure during exporter. I don't see why we wouldn't want to fail early and fast if that is true.

What do you think @natalieparellano ?

**Comment by natalieparellano** [comment]
@jabrown85 I think it makes sense to bring back `cach-image` as an input to analyzer so that we've covered all bases in the "up front validation" category.

@jjbustamante could we change the test to have read/write access to the cache image?
