### ISSUE TITLE
Caching is broken on the lifecycle v0.11.x for buildpacks that implement buildpack API >= 0.6

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/lifecycle#589]
### Summary

On lifecycle v0.11.0 the "opt-in layer caching" feature was introduced (please see https://github.com/buildpacks/rfcs/blob/main/text/0052-opt-in-layer-caching.md and https://github.com/buildpacks/rfcs/blob/main/text/0074-layer-table.md for more information).
As part of this feature, starting from `buildpack API 0.6`, the `types` aren't restored in the analyze phase from the `metadata label` to the `<layer>.toml` file. Buildpacks need to rewrite them (if needed) to the `<layer>.toml` as part of the build phase (buildpack's build script).

Currently, the restorer looks for `cache = true` in the `<layer>.toml` file to determine if it should restore the cache.
This is ok for `buildpack API < 0.6` because, at this phase (after the analyzer ran), `<layer>.toml` includes the same layers types information as the `metadata label`.
Since the `types` aren't restored anymore on lifecycle v0.11.x for buildpacks that implement `buildpack API >= 0.6`, cache layers will never be restored.

In order to fix it, the restorer should read the `types` flags from the `metadata label`.

---

##### Steps

1. Run `pack build` with a buildpack that implements `buildpack API 0.6` and set `cache = true` to one of the layers (under the `[types]` table)
2. Run another `pack build`

##### Current behavior

The layer that set to be cached isn't being restored.

##### Expected

The layer that set to be cached should be restored.

**Comment by natalieparellano** [comment]
There is one edge case that we might need to think carefully about - 

In older (pre-0.6) buildpack API, if a layer is marked `cache = true` in the app metadata, but it is not found in the cache, the layer directory, layer.toml, and layer.sha are all [deleted by the restorer](https://github.com/buildpacks/lifecycle/blob/8d93e588101b22f1e8d3badb9274ebb4bf0894bc/restorer.go#L48). I believe this is necessary so that the buildpack won't think it's a `launch = true` layer that only has the toml file restored. 

If we're using the cache metadata to determine which layers are cached, how could the restorer tell the difference between layers that aren't in the cache but are `launch = true` and layers that aren't in the cache because the app & the cache are not in sync? I don't think it can...
